name: Build Example

on:
  push:
    branches: [ "main", "v2.0.0", "WorkflowTest" ]
  pull_request:
    branches: [ "main", "v2.0.0" ]

env:
  BUILD_TYPE: Sanitizer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install SFML
      run: sudo apt-get install libsfml-dev
    
    - name: Clone GraphicEditor
      run: git clone https://github.com/levasemin/GraphicEditor

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/GraphicEditor/bin -DCMAKE_BUILD_TYPE=Example ./GraphicEditor

    - name: Build
      run: cmake --build ${{github.workspace}}/GraphicEditor/bin

    # - name: Test
